name: Daily Data Processing

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Data
        run: |
          wget -q "https://docs.google.com/spreadsheets/d/1P48quxwMv9XsYQhXjLOvTRRq8tt3ahJnkbXo4VCxjLc/export?format=csv" -O data.csv
          wget -q "https://raw.githubusercontent.com/mbnspocb/611Study-DataCleaner/refs/heads/main/611Study-DataCleaner.py"

      - name: Process Data
        run: |
          python3 611Study-DataCleaner.py data.csv all.csv
          python3 611Study-DataCleaner.py data.csv valid.csv --type valid

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete daily-latest -y || true 
          gh release create daily-latest all.csv valid.csv --title "Daily Data" --notes "Latest processed data"