name: Daily Data Processing

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Download Data
        run: |
          wget -q "https://docs.google.com/spreadsheets/d/1P48quxwMv9XsYQhXjLOvTRRq8tt3ahJnkbXo4VCxjLc/export?format=csv" -O data.csv
          wget -q "https://raw.githubusercontent.com/mbnspocb/611Study-DataCleaner/refs/heads/main/611Study-DataCleaner.py"

      - name: Process Data
        run: |
          python3 611Study-DataCleaner.py data.csv all.csv
          python3 611Study-DataCleaner.py data.csv valid.csv --type valid

      - name: Get UTC+8 date
        id: date
        run: |
         echo "date=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
         echo "tag=$(TZ='Asia/Shanghai' date +'%Y-%m-%d')" >> $GITHUB_OUTPUT


      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          name: "Data Update ${{ steps.date.outputs.date }}"
          body: "处理后数据"
          files: |
              all.csv
              valid.csv
          token: ${{ secrets.GITHUB_TOKEN }}
